CREATE TABLE Users (
    UserId SERIAL PRIMARY KEY,
    UserName VARCHAR NOT NULL,
    UserPassword VARCHAR NOT NULL,
    Email VARCHAR NOT NULL,
    UNIQUE(UserName)
);

CREATE TABLE Books (
    BookId SERIAL PRIMARY KEY,
    Isbn VARCHAR NOT NULL,
    Title VARCHAR NOT NULL,
    Author VARCHAR NOT NULL,
    Year INTEGER NOT NULL,
    UNIQUE(Isbn)
);

CREATE TABLE Reviews (
    ReviewId SERIAL PRIMARY KEY,
    UserKey INTEGER NOT NULL,
    BookKey INTEGER NOT NULL,
    Review INTEGER NOT NULL,
    UNIQUE ( UserKey,BookKey)
);
